import type { VocabEntry } from "../types";

/**
 * Content words: nouns (명사) and proper nouns (고유명사).
 * Romanization follows the Revised Romanization of Korean (RR).
 */
export default [
  { word: "가방", reading: "가방", romaji: "gabang", pos: "noun", en: "bag", zh: "包" },
  { word: "가수", reading: "가수", romaji: "gasu", pos: "noun", en: "singer", zh: "歌手" },
  { word: "것", reading: "것", romaji: "geot", pos: "noun", en: "thing / one", zh: "东西、…的" },
  { word: "고기", reading: "고기", romaji: "gogi", pos: "noun", en: "meat", zh: "肉" },
  { word: "공부", reading: "공부", romaji: "gongbu", pos: "noun", en: "study", zh: "学习" },
  { word: "공원", reading: "공원", romaji: "gongwon", pos: "noun", en: "park", zh: "公园" },
  { word: "기분", reading: "기분", romaji: "gibun", pos: "noun", en: "mood / feeling", zh: "心情" },
  { word: "꽃", reading: "꽃", romaji: "kkot", pos: "noun", en: "flower", zh: "花" },
  { word: "나중", reading: "나중", romaji: "najung", pos: "noun", en: "later (a later time)", zh: "以后、稍后" },
  { word: "날씨", reading: "날씨", romaji: "nalssi", pos: "noun", en: "weather", zh: "天气" },
  { word: "노래", reading: "노래", romaji: "norae", pos: "noun", en: "song", zh: "歌曲" },
  { word: "누나", reading: "누나", romaji: "nuna", pos: "noun", en: "older sister (of a male)", zh: "姐姐(男性称)" },
  { word: "도서관", reading: "도서관", romaji: "doseogwan", pos: "noun", en: "library", zh: "图书馆" },
  { word: "돈", reading: "돈", romaji: "don", pos: "noun", en: "money", zh: "钱" },
  { word: "물", reading: "물", romaji: "mul", pos: "noun", en: "water", zh: "水" },
  { word: "밥", reading: "밥", romaji: "bap", pos: "noun", en: "rice / meal", zh: "饭" },
  { word: "방", reading: "방", romaji: "bang", pos: "noun", en: "room", zh: "房间" },
  { word: "배", reading: "배", romaji: "bae", pos: "noun", en: "stomach / pear / boat (depending on context)", zh: "肚子；梨；船" },
  { word: "비", reading: "비", romaji: "bi", pos: "noun", en: "rain", zh: "雨" },
  { word: "빵", reading: "빵", romaji: "ppang", pos: "noun", en: "bread", zh: "面包" },
  { word: "사람", reading: "사람", romaji: "saram", pos: "noun", en: "person", zh: "人" },
  { word: "산", reading: "산", romaji: "san", pos: "noun", en: "mountain", zh: "山" },
  { word: "선물", reading: "선물", romaji: "seonmul", pos: "noun", en: "gift", zh: "礼物" },
  { word: "선생님", reading: "선생님", romaji: "seonsaengnim", pos: "noun", en: "teacher", zh: "老师" },
  { word: "시간", reading: "시간", romaji: "sigan", pos: "noun", en: "time / hour", zh: "时间" },
  { word: "시험", reading: "시험", romaji: "siheom", pos: "noun", en: "exam / test", zh: "考试" },
  { word: "아버지", reading: "아버지", romaji: "abeoji", pos: "noun", en: "father", zh: "父亲" },
  { word: "어머니", reading: "어머니", romaji: "eomeoni", pos: "noun", en: "mother", zh: "母亲" },
  { word: "어제", reading: "어제", romaji: "eoje", pos: "noun", en: "yesterday", zh: "昨天" },
  { word: "언니", reading: "언니", romaji: "eonni", pos: "noun", en: "older sister (of a female)", zh: "姐姐(女性称)" },
  { word: "여름", reading: "여름", romaji: "yeoreum", pos: "noun", en: "summer", zh: "夏天" },
  { word: "여행", reading: "여행", romaji: "yeohaeng", pos: "noun", en: "travel / trip", zh: "旅行" },
  { word: "영화", reading: "영화", romaji: "yeonghwa", pos: "noun", en: "movie", zh: "电影" },
  { word: "오늘", reading: "오늘", romaji: "oneul", pos: "noun", en: "today", zh: "今天" },
  { word: "오빠", reading: "오빠", romaji: "oppa", pos: "noun", en: "older brother (of a female)", zh: "哥哥(女性称)" },
  { word: "옷", reading: "옷", romaji: "ot", pos: "noun", en: "clothes", zh: "衣服" },
  { word: "우유", reading: "우유", romaji: "uyu", pos: "noun", en: "milk", zh: "牛奶" },
  { word: "운전", reading: "운전", romaji: "unjeon", pos: "noun", en: "driving", zh: "开车、驾驶" },
  { word: "음식", reading: "음식", romaji: "eumsik", pos: "noun", en: "food", zh: "食物" },
  { word: "음악", reading: "음악", romaji: "eumak", pos: "noun", en: "music", zh: "音乐" },
  { word: "의자", reading: "의자", romaji: "uija", pos: "noun", en: "chair", zh: "椅子" },
  { word: "이", reading: "이", romaji: "i", pos: "noun", en: "this / tooth", zh: "这；牙" },
  { word: "전화", reading: "전화", romaji: "jeonhwa", pos: "noun", en: "telephone / call", zh: "电话" },
  { word: "집", reading: "집", romaji: "jip", pos: "noun", en: "house / home", zh: "家、房子" },
  { word: "차", reading: "차", romaji: "cha", pos: "noun", en: "tea / car", zh: "茶；车" },
  { word: "책", reading: "책", romaji: "chaek", pos: "noun", en: "book", zh: "书" },
  { word: "친구", reading: "친구", romaji: "chingu", pos: "noun", en: "friend", zh: "朋友" },
  { word: "카페", reading: "카페", romaji: "kape", pos: "noun", en: "cafe", zh: "咖啡馆" },
  { word: "커피", reading: "커피", romaji: "keopi", pos: "noun", en: "coffee", zh: "咖啡" },
  { word: "키", reading: "키", romaji: "ki", pos: "noun", en: "height", zh: "身高" },
  { word: "편지", reading: "편지", romaji: "pyeonji", pos: "noun", en: "letter", zh: "信" },
  { word: "학교", reading: "학교", romaji: "hakgyo", pos: "noun", en: "school", zh: "学校" },
  { word: "학생", reading: "학생", romaji: "haksaeng", pos: "noun", en: "student", zh: "学生" },
  { word: "한국어", reading: "한국어", romaji: "hangugeo", pos: "noun", en: "Korean (language)", zh: "韩语" },

  // --- proper nouns (고유명사) -------------------------------------------
  { word: "미국", reading: "미국", romaji: "Miguk", pos: "proper-noun", en: "the United States", zh: "美国" },
  { word: "서울", reading: "서울", romaji: "Seoul", pos: "proper-noun", en: "Seoul", zh: "首尔" },
  { word: "한국", reading: "한국", romaji: "Hanguk", pos: "proper-noun", en: "Korea", zh: "韩国" },
] satisfies VocabEntry[];
