// AUTO-GENERATED by scripts/gen-reverse-index.mjs — DO NOT EDIT.
// Reverse index: vocab word → tutorial example sentences that reference it.
// Regenerated on every `pnpm build` / `pnpm dev`.

import type { ExampleRef } from "./types";

export const REVERSE_INDEX: Record<string, ExampleRef[]> = {};
